-- MySQL Script generated by MySQL Workbench
-- Wed Mar 11 16:40:07 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pcs_db_new
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pcs_db_new
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pcs_db_new` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `pcs_db_new` ;

-- -----------------------------------------------------
-- Table `pcs_db_new`.`ADDRESS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcs_db_new`.`ADDRESS` (
  `AddressID` INT NOT NULL,
  `Street` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `State` VARCHAR(45) NOT NULL,
  `Zip` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`AddressID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcs_db_new`.`PATIENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcs_db_new`.`PATIENT` (
  `PatientID` INT NOT NULL,
  `Fname` VARCHAR(45) NOT NULL,
  `Lname` VARCHAR(45) NOT NULL,
  `Birthdate` DATE NOT NULL,
  `SSN` INT(9) UNSIGNED NOT NULL,
  `Sex` SET('male','female','m','f') NOT NULL,
  `Sectioned?` TINYINT(1) NOT NULL DEFAULT 0,
  `PatientNum` VARCHAR(6) NOT NULL COMMENT 'Patient’s identification number, similar to our student Mocs ID.',
  `AddressID` INT NOT NULL,
  PRIMARY KEY (`PatientID`),
  UNIQUE INDEX `SSN_UNIQUE` (`SSN` ASC),
  INDEX `fk_PATIENT_ADDRESS_idx` (`AddressID` ASC),
  CONSTRAINT `fk_PATIENT_ADDRESS`
    FOREIGN KEY (`AddressID`)
    REFERENCES `pcs_db_new`.`ADDRESS` (`AddressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcs_db_new`.`CLINIC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcs_db_new`.`CLINIC` (
  `ClinicID` INT NOT NULL,
  `ClinicName` VARCHAR(45) NOT NULL,
  `AddressID` INT NOT NULL,
  INDEX `fk_CLINIC_ADDRESS1_idx` (`AddressID` ASC),
  PRIMARY KEY (`ClinicID`),
  CONSTRAINT `fk_CLINIC_ADDRESS1`
    FOREIGN KEY (`AddressID`)
    REFERENCES `pcs_db_new`.`ADDRESS` (`AddressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcs_db_new`.`EMPLOYEE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcs_db_new`.`EMPLOYEE` (
  `EmployeeID` INT NOT NULL AUTO_INCREMENT,
  `Fname` VARCHAR(45) NOT NULL,
  `Lname` VARCHAR(45) NOT NULL,
  `UserType` SET('AR', 'EM', 'Doctor', 'Nurse', 'MRS') NOT NULL,
  `ClinicID` INT NOT NULL,
  PRIMARY KEY (`EmployeeID`),
  INDEX `fk_EMPLOYEE_CLINIC1_idx` (`ClinicID` ASC),
  CONSTRAINT `fk_EMPLOYEE_CLINIC1`
    FOREIGN KEY (`ClinicID`)
    REFERENCES `pcs_db_new`.`CLINIC` (`ClinicID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcs_db_new`.`APPOINTMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcs_db_new`.`APPOINTMENT` (
  `AppointmentID` INT NOT NULL AUTO_INCREMENT,
  `AppTime` DATETIME NOT NULL,
  `ShowedUp` TINYINT(1) NULL DEFAULT 0,
  `ClinicID` INT NOT NULL,
  `PatientID` INT NOT NULL,
  `EmployeeID` INT NOT NULL,
  PRIMARY KEY (`AppointmentID`),
  INDEX `fk_APPOINTMENT_PATIENT1_idx` (`PatientID` ASC),
  INDEX `fk_APPOINTMENT_EMPLOYEE1_idx` (`EmployeeID` ASC),
  CONSTRAINT `fk_APPOINTMENT_PATIENT1`
    FOREIGN KEY (`PatientID`)
    REFERENCES `pcs_db_new`.`PATIENT` (`PatientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_APPOINTMENT_EMPLOYEE1`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `pcs_db_new`.`EMPLOYEE` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcs_db_new`.`MED_RECORD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcs_db_new`.`MED_RECORD` (
  `RecordID` INT NOT NULL AUTO_INCREMENT,
  `PatientID` INT NOT NULL,
  PRIMARY KEY (`RecordID`),
  INDEX `fk_RECORD_PATIENT1_idx` (`PatientID` ASC),
  CONSTRAINT `fk_RECORD_PATIENT1`
    FOREIGN KEY (`PatientID`)
    REFERENCES `pcs_db_new`.`PATIENT` (`PatientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcs_db_new`.`ALLERGY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcs_db_new`.`ALLERGY` (
  `AllergyID` INT NOT NULL AUTO_INCREMENT,
  `AllergyName` VARCHAR(45) NOT NULL,
  `Severity` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AllergyID`),
  UNIQUE INDEX `AllergyID_UNIQUE` (`AllergyID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcs_db_new`.`MEDICATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcs_db_new`.`MEDICATION` (
  `MedicationID` INT NOT NULL,
  `CommonName` VARCHAR(45) NOT NULL,
  `Side Effects` TEXT NOT NULL,
  `Dosage` VARCHAR(20) NOT NULL,
  `TimesPerDay` VARCHAR(45) NOT NULL,
  `ActiveRx` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`MedicationID`, `CommonName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcs_db_new`.`MED_RECORD_has_ALLERGY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcs_db_new`.`MED_RECORD_has_ALLERGY` (
  `RecordID` INT NOT NULL,
  `AllergyID` INT NOT NULL,
  PRIMARY KEY (`RecordID`, `AllergyID`),
  INDEX `fk_MED_RECORD_has_ALLERGY_ALLERGY1_idx` (`AllergyID` ASC),
  INDEX `fk_MED_RECORD_has_ALLERGY_MED_RECORD1_idx` (`RecordID` ASC),
  CONSTRAINT `fk_MED_RECORD_has_ALLERGY_MED_RECORD1`
    FOREIGN KEY (`RecordID`)
    REFERENCES `pcs_db_new`.`MED_RECORD` (`RecordID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MED_RECORD_has_ALLERGY_ALLERGY1`
    FOREIGN KEY (`AllergyID`)
    REFERENCES `pcs_db_new`.`ALLERGY` (`AllergyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcs_db_new`.`TREATMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcs_db_new`.`TREATMENT` (
  `TreatmentID` INT NOT NULL AUTO_INCREMENT,
  `Diagnosis` TINYTEXT NOT NULL,
  `Description` TEXT NOT NULL COMMENT 'Description of the treatment',
  `Duration` VARCHAR(45) NOT NULL COMMENT 'Duration of the treatment',
  `Ongoing?` TINYINT(1) NOT NULL COMMENT 'Is it an ongoing treatment?',
  `DateDiagnosed` DATE NULL,
  PRIMARY KEY (`TreatmentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcs_db_new`.`TREATMENT_has_MEDICATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcs_db_new`.`TREATMENT_has_MEDICATION` (
  `TREATMENT_TreatmentID` INT NOT NULL,
  `MEDICATION_MedicationID` INT NOT NULL,
  `MEDICATION_CommonName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TREATMENT_TreatmentID`, `MEDICATION_MedicationID`, `MEDICATION_CommonName`),
  INDEX `fk_TREATMENT_has_MEDICATIONS_MEDICATIONS1_idx` (`MEDICATION_MedicationID` ASC, `MEDICATION_CommonName` ASC),
  INDEX `fk_TREATMENT_has_MEDICATIONS_TREATMENT1_idx` (`TREATMENT_TreatmentID` ASC),
  CONSTRAINT `fk_TREATMENT_has_MEDICATIONS_TREATMENT1`
    FOREIGN KEY (`TREATMENT_TreatmentID`)
    REFERENCES `pcs_db_new`.`TREATMENT` (`TreatmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TREATMENT_has_MEDICATIONS_MEDICATIONS1`
    FOREIGN KEY (`MEDICATION_MedicationID` , `MEDICATION_CommonName`)
    REFERENCES `pcs_db_new`.`MEDICATION` (`MedicationID` , `CommonName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcs_db_new`.`LOGIN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcs_db_new`.`LOGIN` (
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(65) NOT NULL,
  `EMPLOYEE_EmployeeID` INT NOT NULL,
  PRIMARY KEY (`Username`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC),
  UNIQUE INDEX `Password_UNIQUE` (`Password` ASC),
  INDEX `fk_LOGIN_EMPLOYEE1_idx` (`EMPLOYEE_EmployeeID` ASC),
  CONSTRAINT `fk_LOGIN_EMPLOYEE1`
    FOREIGN KEY (`EMPLOYEE_EmployeeID`)
    REFERENCES `pcs_db_new`.`EMPLOYEE` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcs_db_new`.`SECTIONED`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcs_db_new`.`SECTIONED` (
  `SectionID` INT NOT NULL AUTO_INCREMENT,
  `PatientID` INT NOT NULL,
  `ClinicID` INT NOT NULL,
  `EmployeeID` INT NOT NULL COMMENT '				',
  `DateSectioned` DATETIME NOT NULL,
  `DateReleased` DATETIME NULL,
  `RoomNumber` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`SectionID`),
  INDEX `fk_SECTIONED_EMPLOYEE1_idx` (`EmployeeID` ASC),
  INDEX `fk_SECTIONED_PATIENT1_idx` (`PatientID` ASC),
  INDEX `fk_SECTIONED_CLINIC1_idx` (`ClinicID` ASC),
  CONSTRAINT `fk_SECTIONED_CLINIC1`
    FOREIGN KEY (`ClinicID`)
    REFERENCES `pcs_db_new`.`CLINIC` (`ClinicID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SECTIONED_EMPLOYEE1`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `pcs_db_new`.`EMPLOYEE` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SECTIONED_PATIENT1`
    FOREIGN KEY (`PatientID`)
    REFERENCES `pcs_db_new`.`PATIENT` (`PatientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcs_db_new`.`ACTIVITY_LOG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcs_db_new`.`ACTIVITY_LOG` (
  `LogID` INT NOT NULL AUTO_INCREMENT,
  `ActivityType` SET('AllergyEdit', 'UserLogin','UserAdded','Treatment') NOT NULL,
  `EmployeeID` INT NOT NULL,
  `AllergyID` INT NULL,
  `TimeStamp` DATETIME NOT NULL,
  `TreatmentID` INT NULL,
  PRIMARY KEY (`LogID`),
  UNIQUE INDEX `LogID_UNIQUE` (`LogID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcs_db_new`.`MED_RECORD_has_TREATMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcs_db_new`.`MED_RECORD_has_TREATMENT` (
  `MED_RECORD_RecordID` INT NOT NULL,
  `TREATMENT_TreatmentID` INT NOT NULL,
  PRIMARY KEY (`MED_RECORD_RecordID`, `TREATMENT_TreatmentID`),
  INDEX `fk_MED_RECORD_has_TREATMENT_TREATMENT1_idx` (`TREATMENT_TreatmentID` ASC),
  INDEX `fk_MED_RECORD_has_TREATMENT_MED_RECORD1_idx` (`MED_RECORD_RecordID` ASC),
  CONSTRAINT `fk_MED_RECORD_has_TREATMENT_MED_RECORD1`
    FOREIGN KEY (`MED_RECORD_RecordID`)
    REFERENCES `pcs_db_new`.`MED_RECORD` (`RecordID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MED_RECORD_has_TREATMENT_TREATMENT1`
    FOREIGN KEY (`TREATMENT_TreatmentID`)
    REFERENCES `pcs_db_new`.`TREATMENT` (`TreatmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'Master' IDENTIFIED BY 'masterpass';

GRANT ALL ON `pcs_db_new`.* TO 'Master';
CREATE USER 'Login' IDENTIFIED BY 'loginpass';

GRANT SELECT ON TABLE `pcs_db_new`.* TO 'Login';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
